
sharding:
  jdbc:
    dataSource:
      names: db-test0,db-test1
      # 主机
      db-test0: #org.apache.tomcat.jdbc.pool.DataSource
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/spring_cloud3?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT
        username: root
        password: 123456
        #连接最大池
        maxPoolSize: 20
      db-test1: # 从库
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3307/spring_cloud3?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT
        username: root
        password:
        maxPoolSize: 20
#      db-test2: # \u914D\u7F6E\u7B2C\u4E8C\u4E2A\u4ECE\u5E93
#        type: com.alibaba.druid.pool.DruidDataSource
#        driverClassName: com.mysql.jdbc.Driver
#        url: jdbc:mysql://127.0.0.1:3307/spring_cloud3?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT
#        username: root
#        password: 123456
#        maxPoolSize: 20
    config:
      masterslave: # \u914D\u7F6E\u8BFB\u5199\u5206\u79BB
        load-balance-algorithm-type: round_robin # \u914D\u7F6E\u4ECE\u5E93\u9009\u62E9\u7B56\u7565\uFF0C\u63D0\u4F9B\u8F6E\u8BE2\u4E0E\u968F\u673A\uFF0C\u8FD9\u91CC\u9009\u62E9\u7528\u8F6E\u8BE2//random \u968F\u673A //round_robin \u8F6E\u8BE2
        name: db1s2
        master-data-source-name: db-test0
        slave-data-source-names: db-test1
    props:
      sql: # \u5F00\u542FSQL\u663E\u793A\uFF0C\u9ED8\u8BA4\u503C: false\uFF0C\u6CE8\u610F\uFF1A\u4EC5\u914D\u7F6E\u8BFB\u5199\u5206\u79BB\u65F6\u4E0D\u4F1A\u6253\u5370\u65E5\u5FD7\uFF01\uFF01\uFF01
        show: true

#\u6307\u5B9Amapper\u6620\u5C04\u6587\u4EF6
mybatis:
  mapper-locations: classpath:mapper/*.xml